# Generated by Django 3.1 on 2020-11-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rank',
            new_name='score',
        ),
    ]
